name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '32 18 * * 4'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev eslint@8.10.0
          npm install --save-dev @microsoft/eslint-formatter-sarif@3.1.0
          npm install --save-dev @typescript-eslint/parser@^5.0.0
          npm install --save-dev @typescript-eslint/eslint-plugin@^5.0.0

      - name: Create ESLint configuration file
        run: |
          cat > .eslintrc.js << 'EOF'
          module.exports = {
            parser: '@typescript-eslint/parser',
            plugins: ['@typescript-eslint'],
            extends: [
              'eslint:recommended',
              '@typescript-eslint/recommended'
            ],
            parserOptions: {
              ecmaVersion: 2020,
              sourceType: 'module',
              ecmaFeatures: {
                jsx: true
              }
            },
            env: {
              browser: true,
              es6: true,
              node: true
            },
            rules: {
              // Можете добавить свои правила здесь
            },
            ignorePatterns: [
              'node_modules/',
              'dist/',
              'build/',
              '*.min.js'
            ]
          };
          EOF

      - name: Run ESLint
        run: |
          npx eslint . \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
            --no-error-on-unmatched-pattern
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
